### ISSUE TITLE
[BUG] Lockscreen hangs when unlocked with fingerprint

### ISSUE THREAD

**Issue by ericswpark** [BlissRoms/bug_reports#1]
Under certain conditions, unlocking with fingerprint will cause the lockscreen to hang. In this situation, you cannot fully unlock the phone, and can only interact with the notifications and quick settings. The only way to unlock the phone is to re-lock the phone with the power button and then unlock using PIN/pattern.

**Steps To Reproduce**

1. Unlock with fingerprint

**Expected behavior**

Phone unlocks

**Device:**

 - Codename (ex. bullhead): bullhead
 - Build date (ex. 20200204): 20200225

**Additional information**

Seems to affect multiple devices. Please leave a comment below with device information if your device is affected.

**Comment by rcstar6696** [comment]
Same bug on clover jasmine and wayne...
All versions of bliss 12

**Comment by ericswpark** [comment]
Seems to be fixed on the latest release of BlissRoms 12.7/12.8, anybody with the same issue still? If nobody comments then this bug will be closed in a couple of days.

**Comment by rcstar6696** [comment]
No freeze in 12.8 on my devices

**Comment by ericswpark** [comment]
Great, thank you for confirming!
