### ISSUE TITLE
[BUG] Bluetooth handsfree connection shows no signal & no network.

### ISSUE THREAD

**Issue by georgep56** [BlissRoms/bug_reports#10]
I'm using Bliss version 12.7 on Xiaomi Redmi Note 3 (kenzo).
Important to note that the same issue also exists with Havoc v3.5 

When connected to my in-car bluetooth handsfree (factory-fit Nissan Connect) the display mostly shows zero signal and 'No Network' yet the handsfree functionality works fine.
Very occasionally on connecting the correct signal level and network (Vodafone UK) is displayed, although this will soon disappear and revert to no signal / no network.

Whether the phone display is on or not seems to make no difference, though I can't conform this 100% as I mostly just jump in to the car and drive without looking at the phone.

**Steps To Reproduce**

1. Take the normally running phone to the car and turn on the engine. Display will show zero signal on the in-car display signal meter; selecting phone functionality shows 'No Network'. Unlocking the phone makes no difference. 

Calls can be received and made normally using the in-car interface. Contact information and call history is correctly synchronised with the in-car unit.

**Expected behavior**

In-car display should show a continually varying signal level and should display the correct network name.

**Screenshots**

**Device:**

 - Codename (ex. bullhead): kenzo 
 - Build date (ex. 20200204): 20200517

**Additional information**

**Comment by ericswpark** [comment]
Hello, this is a bug with a specific device. Please file this issue with the respective device repository. Thanks!
