### ISSUE TITLE
Call recording is distorted and inaudible

### ISSUE THREAD

**Issue by ldgcolt** [BlissRoms/bug_reports#11]
Call recordings in dialer of 22/05 ROM are distorted and inaudible.

**Comment by ericswpark** [comment]
Please provide more information. Please follow our bug reporting template if you need help. If no actionable information is given this bug report will be closed in a couple of days.

**Comment by ericswpark** [comment]
Closing due to no response. If you want to re-open this bug, please supply further information in a comment.

**Comment by ldgcolt** [comment]
Calls are recorded but when the recorded calls are played,nothing is heard.No voice,no sound,nothing is audible.Same issue for the latest update of Bliss which is dated 17/06/2020.

**Comment by ldgcolt** [comment]
Hi Eric,

Calls are recorded but when the recorded calls are played,nothing is
heard.No voice,no sound,nothing is audible.Same issue for the latest update
of Bliss which is dated 17/06/2020.

On Sunday, 21 June 2020, Eric Park <notifications@github.com> wrote:
> Closed #11.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/-svXwSlH-I7B-RscOce_DsSYVEFZDU4aBxni9DNAjfUHjhrRiLhiRf5QFDhdgbLEX_VvE_Y91VAXQ7RKTyxGakZTcDCvYP8O1zVEtwloxrkwZqwcftI9AORHUHXAgkPMwSiekXxUX22KBNx5IjjkBwtNbYvWfryOwpzfD7gab_6ayLusxsIm3UCqJsffvE58pOiRIHSxespihYHgDCA52xbfpOTkuf7NDpO8XafKegJdlqnBDD4eXZZFtIqV7pU=s0-d-e1-ft#https://github.com/notifications/beacon/AGJDJCT36YW46X7MZKHBBITRXVBHLA5CNFSM4NITVOXKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOZ2EOR4I.gif>

**Comment by ericswpark** [comment]
Sorry, but that is not enough information. Please submit a new bug report and follow the template, making sure to include devices information. This bug will remain closed.
