### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by naeemgithub0** [BlissRoms/bug_reports#12]
Charging slowly and battery temperature reaching 42 degree 

**Steps To Reproduce**

1. 
2. 

**Expected behavior**
 fast charging and normal battery temperature.   

**Screenshots**

**BlissRoms source:**
https://sourceforge.net/projects/blissroms/files/Q/phoenix/Bliss-v12.7-phoenix-OFFICIAL-20200506.zip/download

 - Link to last merged Gerrit commit: 

**Device:**
poco x2

 - Codename (ex. bullhead):  Phoenix 
 - Build date (ex. 20200204): 
bliss_phoenix-userdebug 10 QQ2A.200501.001.B2 
**Additional information**
 fingerprints ghost touch issue

**Comment by ericswpark** [comment]
Sorry, but fast charging normally produces a bit of heat. This is normal. The report will now be closed.
