### ISSUE TITLE
[BUG] Santoni Fingerprint not recognised

### ISSUE THREAD

**Issue by Rohitpag** [BlissRoms/bug_reports#14]
**Steps To Reproduce**
1. Go to setting > Security
2. Go to fingerprint
3. Filled all details to print fingerprint

**Expected behavior**
Fingerprint setting option should be able to print Fingerprints

**Device:**
Redmi 4x
 - Codename (Santoni):  
 - Build date (20200505): 

**Additional information**
Bug logs
https://t.co/pseyQsxrXP?amp=1

**Comment by ericswpark** [comment]
Hello, this is a bug for an individual device. Please file a bug report in the device's repository's issue section. Thanks!
