### ISSUE TITLE
[BUG] No DATA available ( 3G / 4G connection ) after night power off and after Airplane mode

### ISSUE THREAD

**Issue by dgx3d** [BlissRoms/bug_reports#15]
When I power on the phone in the morning I have no DATA available ( 3G / 4G connection ), I have to reset the network configuration, it also happening when I leave the Airplane mode after a long time

**Steps To Reproduce**

**_1.  Power off the phone , leave it all the night and power on in the morning
2.  Put the phone in Airplane mode for a while ( long time ), then turn off the Airplane mode_**

**Expected behavior**

**_No DATA available ( 3G / 4G connection )_** 

**Screenshots**
**_I have no screeshot now, but what I see is no 4G or any kind of connection icon in the status bar._**

**Device:**

- Codename (ex. bullhead):  **_I01WD ( Asus Zenfone6 )_**
- Build date (ex. 20200204): **_20200520_**

**Additional information**

**_I'm on Bliss Rom 12.7 20200520 on Asus Zenfone6 8/256 ( I01WD )_**

**Comment by ericswpark** [comment]
Sorry, but this is a device-side bug. Please file the bug in the respective device repository. Thank you!
