### ISSUE TITLE
Hi, when face detection is active, it doesn't work properly to quickly launch the camera by double-clicking the power button. I have 12.7 OnePlus 6 I don't know if it's an error but together it doesn't work writes the "camera is running"🤔[BUG]

### ISSUE THREAD

**Issue by Pepa77** [BlissRoms/bug_reports#16]
**Steps To Reproduce**

1. 
2. 

**Expected behavior**

**Screenshots**

**BlissRoms source:**

 - Link to last merged Gerrit commit: 

**Device:**

 - Codename (ex. bullhead):  
 - Build date (ex. 20200204): 

**Additional information**

**Comment by ericswpark** [comment]
Hello, this is not the proper way of filling out a bug report. This report will now be closed. 

For user support, please visit our Telegram chats.

If you believe the bug is with your specific device, please file a GitHub Issue with the respective device repository. Thanks!
