### ISSUE TITLE
[BUG] No "touch interface" after selected notification from lockscreen and unlock via pattern or fingerprint 

### ISSUE THREAD

**Issue by dgx3d** [BlissRoms/bug_reports#17]
**_Some times it's impossibile to use the touch screen after a lockscreen selection of a notification that requires unlock via pattern or fingerprint. The screen is stuck and the only way is to put the devices in sleep mode with power and turn on again._**

**_Only QSettings works ( swiping top / down ) and the navigation bar_**

**Steps To Reproduce**

**_1. A new notification shown on the Lockscreen
2. Select notification on the Lockscreen to open the relative application
3. Insert pattern or use finger print authentication
4. In the Homescreen all is "untouchable" can't swipe or press any icon_**

**Expected behavior**

**_The screen is stuck, touch screen seems dead and the only way is to put the devices in sleep mode with power and turn on again. Only QSettings works ( swiping top / down ) and the navigation bar_**

**Screenshots**

**_No screen shot available_**

**Device:**

 - Codename (ex. bullhead):  **_I01WD ( Asus ZenFone6 )_**
 - Build date (ex. 20200204): **_20200520_**

**Additional information**

**_I'm on Bliss Rom 12.7 20200520 on Asus Zenfone6 8/256 ( I01WD )_**

**Comment by rohanpurohit** [comment]
This should be fixed in latest 12.8 version for your device

**Comment by dgx3d** [comment]
Hi Rohan,

Thank you I'll try as soon as I can.


Best a regards, Fausto.

**Comment by ericswpark** [comment]
Fixed in 12.8. Closed unless regression occurs. Please file a new bug if you find a regression!
