### ISSUE TITLE
aod date widget bug

### ISSUE THREAD

**Issue by zaazaabr** [BlissRoms/bug_reports#18]
if i select a clock style with date widget included and turn off date from outside option ... then lockscreen is ok but in aod its showing date widget

**Comment by rohanpurohit** [comment]
This is intended behaviour. Date widget is forced in ambient/doze as date widget (the view also contains music/track info/artist) etc, if u disable date widget on ambient u also lose the music info on ambient/aod screen , and consequently features like ambient pulse on new tracks among others become redundant. I hope this solves your query
