### ISSUE TITLE
Pubg crash

### ISSUE THREAD

**Issue by ghost** [BlissRoms/bug_reports#19]
After flashing bliss rom android 10 for tissot pubg crashes 
I also hide magisk
And hide magisk from pubg and ogher gapps
Other games working fine

*
**Expected behavior**

**Device:**

 - Codename (ex. bullhead):  tissot
 - Build date (ex. 20200204):  @20200523
[Log_2020-05-27_02-06-35.txt](https://github.com/BlissRoms/bug_reports/files/4695992/Log_2020-05-27_02-06-35.txt)

**Additional information**

**Comment by ericswpark** [comment]
Hello, this is an issue with a specific device, not the ROM itself. Please go to the respective device repository and file a bug report there. Thanks!
