### ISSUE TITLE
[BUG] Lockscreen hangs when set to none

### ISSUE THREAD

**Issue by srgrusso** [BlissRoms/bug_reports#2]
Under certain conditions, when the lockscreen security is set to none it will cause the lockscreen to hang. In this situation, you cannot fully unlock the phone, and can only interact with the notifications and quick settings. The only way to unlock the phone is to adjust the screen brightness or restart the systemui

**Steps To Reproduce**

Set lockscreen security to none and wait for it to lock.

**Expected behavior**

Unlock device and resume normal function.

**Screenshots**

**BlissRoms source:**

**Device:**

 - Codename (ex. bullhead):  gtaxllte/gtaxlwifi
 - Build date (ex. 20200204): 

**Additional information**

This issue was first reported to me on 1-13-2020 and I can confirm this issue. It has been mentioned that it exists on other devices too. Please list your device if you are affected.

**Comment by digoloco** [comment]
this always happens to me also in the bliss rom i don't know what reason, but having this problem even today,the screen is flashing and you can't do anything on the device!

**Comment by ericswpark** [comment]
Seems to be fixed in recent builds, can anybody repro?

**Comment by srgrusso** [comment]
I have been testing for a day now and haven't had an issue. Can we hope?

**Comment by ericswpark** [comment]
Since nobody could repro closing for now. Feel free to comment if anything changes and I will re-open!
