### ISSUE TITLE
[BUG] : Pretty long booting time

### ISSUE THREAD

**Issue by sagarRL1** [BlissRoms/bug_reports#21]
Every time I reboot my phone, boot time is very long.
Device: violet

**Steps To Reproduce**
 

1. Reboot
2. 

**Expected behavior**

Boot time to be shorter

**Screenshots**

**BlissRoms source:**

 - Link to last merged Gerrit commit: 

**Device:**

 - Codename (ex. bullhead):  violet
 - Build date (ex. 20200204): 20200513

**Additional information**

**Comment by ericswpark** [comment]
Hello, this is a bug with a specific device. Please file this issue with the respective device repository. Thanks!
