### ISSUE TITLE
[FR] Floating windows

### ISSUE THREAD

**Issue by sagarRL1** [BlissRoms/bug_reports#22]
**Describe the feature:**

Floating windows or freeform window.
Although freeform windows can be activated from developer option, buy it is not quite stable and most of the time it is difficult to use or can't be used.

**Links to commits (if applicable):**
 this feature can be found in Miui roms

**Additional information**

![IMG_20200529_154923_690](https://user-images.githubusercontent.com/66117935/83249294-03584580-a1c4-11ea-810f-85f6e1c885fc.jpg)

**Comment by rohanpurohit** [comment]
freeform windows are pretty decent the way they are.. more functionality wont be added :)
