### ISSUE TITLE
Ghost touch while gaming

### ISSUE THREAD

**Issue by lalith20** [BlissRoms/bug_reports#23]
When I play pubg Mobile (game) the crosshair (aim) moves automatically even if I didn't move it, it just shakes up and like flickering . This happens even when
gyroscope is off 

**Expected behavior**

It was supposed to aim on target and should move until we touch or swipe one the screen
[glitch video.zip](https://github.com/BlissRoms/bug_reports/files/4701279/glitch.video.zip)

**Screenshots**

**Device:**

 - Codename (lavender):  
 - Build date (20200528): 

**Additional information**

I am adding a video proof in a .zip format extract it and you can understand the glitch hope you will fix it soon
[glitch video.zip](https://github.com/BlissRoms/bug_reports/files/4701318/glitch.video.zip)

**Comment by ericswpark** [comment]
Hello, this is a bug with a specific device, specifically the touch screen, which may not have been calibrated properly. Please file this issue with the respective device repository. Thanks!

**Comment by lalith20** [comment]
> Hello, this is a bug with a specific device, specifically the touch screen, which may not have been calibrated properly. Please file this issue with the respective device repository. Thanks!

bro but it works fine in stock rom for redmi note 7s

**Comment by ericswpark** [comment]
Yes, it would work fine on the stock ROM because the touch screen is calibrated by the manufacturer. Again, this is not a ROM-side bug, but something you need to file with the respective device repository. Please go to the Redmi Note 7s repository and open a bug report there. Thanks!
