### ISSUE TITLE
BUG LED NOTIFICATION TULIP

### ISSUE THREAD

**Issue by supersub10** [BlissRoms/bug_reports#24]
Hi i have redmi note 6 pro (tulip) I have a problem on the notification LED that is not functioning properly. Like when charging, incoming calls or incoming notifications. Notification LED does not work. I hope to be able to overcome and fix this notification LED bug and I hope that the improvement update will come and bring happiness as the meaning of this ROM is Bliss Rom [Bug]

**Comment by ericswpark** [comment]
Hello, this is a bug with a specific device. Please file this issue with the respective device repository. Thanks!
