### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adnanrinaldi** [BlissRoms/bug_reports#25]
Hi, I want to report a bug, I'm using redmi note 4x (mido) on with BlissRom build date May 25 2020. When I used my phone, sometime in sudden the cellular data gone and reappear in few seconds, it's quite disturbing when I played game. Thank you in advance

**Comment by ericswpark** [comment]
Hello, this is a bug with a specific device. Please file a GitHub Issue in the respective device's repository page. Thanks!
