### ISSUE TITLE
[FR] Sound boost

### ISSUE THREAD

**Issue by SRI-RO** [BlissRoms/bug_reports#26]
**Describe the feature:**

**Links to commits (if applicable):**

**Additional information**

Hello,
it is an interesting rom, but you should also work on the sound side, the sound is a bit weak and a bit cold. the sound should be richer, clearer, and louder.
when you listen to a song on the speaker, make the sound louder and richer
Thank you I wish you good health!👏👏👏

**Comment by ericswpark** [comment]
Hello, this is not something that can be fixed or changed ROM-side. Sound boosting is generally done on the device-side, and if not done properly it can cause damage to hardware. This report will now be closed.
