### ISSUE TITLE
[FR] Increase the number of notification icons on the left of statusbar

### ISSUE THREAD

**Issue by bomzhellino** [BlissRoms/bug_reports#27]
Only 4 notification icons appear on the left of statusbar even when the clock is on the right.
Please increase this number.
![Statusbar](https://user-images.githubusercontent.com/65486397/83331426-083df780-a29f-11ea-9165-eded644f0942.jpg)

**Comment by rohanpurohit** [comment]
Which device? It can be fixed in the next update

**Comment by rohanpurohit** [comment]
closing ! u can still comment your device name and the maintainer of same will be informed to increase the icons , and change reflected in next build

**Comment by bomzhellino** [comment]
> closing ! u can still comment your device name and the maintainer of same will be informed to increase the icons , and change reflected in next build
Sorry. I thought this feature was device independent. My device is daisy.
I will contact maintainer myself.
Thank you!
