### ISSUE TITLE
[BUG] Animation of Quick Settings when device is in landscape

### ISSUE THREAD

**Issue by efirium2018** [BlissRoms/bug_reports#29]
**Animation bug**

There is a bug with the animation of opening and closing quick settings in a horizontal form.  And the elements in the screenshot are very close to the buttons, it doesn’t look good

**Screenshots**
![Screenshot_20200531-015001_YouTube (1)](https://user-images.githubusercontent.com/48407418/83340521-f29df180-a2e1-11ea-8374-289eb642d428.jpg)

https://streamable.com/otd4fv

**Device:**
santoni
latest build

**Comment by rohanpurohit** [comment]
https://github.com/BlissRoms/platform_frameworks_base/commit/613127f84c3e7ebd820f6e5950532ce1a79aa997
