### ISSUE TITLE
[BUG] Bliss Launcher freezing when opening recent app

### ISSUE THREAD

**Issue by Aanridwan96** [BlissRoms/bug_reports#31]
I got weird bug in bliss 12.7 .
Several times I got freeze when opening recent app (especially when telegram was open).
After I changed to other launcher , I didn't experience it anymore

**Comment by ericswpark** [comment]
Hello, can you supply logcat? Thanks!

**Comment by ericswpark** [comment]
No response for a week, closing. Please comment to re-open this bug.
