### ISSUE TITLE
[BUG] Statusbar icons have different margins on home and lock screens

### ISSUE THREAD

**Issue by dgx3d** [BlissRoms/bug_reports#32]
**_The statusbar right icons are not in the same place in the lockscreen and inthe homescreen._**

**Screenshots**

![20200601_Statusbar ICONS not in the same place - BLISSROM](https://user-images.githubusercontent.com/66011079/83438175-4246ff00-a441-11ea-8083-18d7e2efff2d.jpg)

**Device:**

 - Codename (ex. bullhead):  **_I01WD ( Asus Zenfone6 )_**
 - Build date (ex. 20200204): **_20200520_**

**Additional information**

**_I'm on Bliss Rom 12.7 20200520 on Asus Zenfone6 8/256 ( I01WD )_**

**Comment by rohanpurohit** [comment]
This can be controlled with blissify> more > rounded corners > statusbar content padding.. set it to 0 if u don't want any padding!

**Comment by dgx3d** [comment]
Hi Rohan,

this can work on the home screen, but nothing happen on the Lock screen.

Best regards, Fausto.
