### ISSUE TITLE
[BUG] Orientation sensors off 90 degrees clockwise

### ISSUE THREAD

**Issue by wanderingconfused** [BlissRoms/bug_reports#33]
I am testing Bliss-OS 11.11 (x86_64) on an ASUS TP300LD laptop.  If I allow orientation to be controlled by the sensors the orientation is 90 rotated by 90 degrees clockwise, ie when flat the bottom of the screen is on the left hand side.  Aside from the rotation being off the orientation behaves as expected.  

The laptop uses the iio modules inv_mpu6050, and ak8975. The orientation behaves as expected in Ubuntu as well.  

I also had the same issue in Android x86, however I was able to solve it by patching some lines of code in hardware/libsensors/iio-sensors.cpp

`data[i].acceleration.x = -scale * read_sysfs_int("in_accel_x_raw");
data[i].acceleration.y = scale * read_sysfs_int("in_accel_y_raw");`

was switched to 

`data[i].acceleration.x = -scale * read_sysfs_int("in_accel_y_raw");
data[i].acceleration.y = -scale * read_sysfs_int("in_accel_x_raw");`

I am downloading the source and will be poking around as I have free time,  but anything that helps point me in the right direction would be appreciated.

**Expected behavior**

The screen orientation coincides with the laptop orientation

**Device:**

Asus TP300LD

**Comment by electrikjesus** [comment]
You will need to add your $PRODUCT to the init.sh file, like you see here, with the correct orientation settings: https://github.com/BlissRoms-x86/device_generic_common/blob/p9.0-11.12/init.sh#L315

**Comment by ericswpark** [comment]
Closing due to answer provided above and it being a device-side bug. Thanks!
