### ISSUE TITLE
[BUG] phoenix screen cast not working

### ISSUE THREAD

**Issue by San0621** [BlissRoms/bug_reports#35]
When i turn on wifi and blutooth screen cast tile remains faded not turning on

**Screenshots**
https://drive.google.com/file/d/1-GVL68RIiWg6jv46R4FztAlKoqAs1TZF/view?usp=drivesdk

*Device:**
 - Codename (phoenix):  
 - Build date (20200610)
**Logs**
https://drive.google.com/file/d/1-7-Vs7d44FbdvZfZHGwwmpQtN2XpkK4v/view?usp=drivesdk

**Comment by ericswpark** [comment]
Hello, this is a bug with a specific device. Please file this issue with the respective device repository. Thanks!
