### ISSUE TITLE
aptx Adaptive not working

### ISSUE THREAD

**Issue by Boothuss** [BlissRoms/bug_reports#40]
No sound from Bluetooth buds. When HD audio is disabled buds work. Clean install.

**Comment by UknowEtheG** [comment]
Which device are you running?
Which specific build is installed?
Have you reached out to the maintainer for your device regarding this? <~~please seek support from your device's maintainer.

Great place to start: 
https://t.me/Team_Bliss_Community

Many useful group "notes" containing tons of device specific info including who to and how to contact regarding the maintainer
