### ISSUE TITLE
[BUG]  volte not working

### ISSUE THREAD

**Issue by ghost** [BlissRoms/bug_reports#41]
## Steps To Reproduce
1. 
2. 
3. 
4. 

## Expected Behavior

```
Edit here
```

## Current Behavior

```
Edit here
```

## Possible Solution

```
Edit here
```

## Screenshots

```
Edit here
```

## Device Details (please complete the following information)

* Device: [e.g. Pixel 4a]
* Codename: [e.g. sunfish]
* Build Date: [e.g. Bliss-v15.0-sunfish-OFFICIAL-gapps-20220102]

**Comment by ericswpark** [comment]
Please re-file the issue with the details filled out.
