### ISSUE TITLE
[BUG] Asked 4 times for the SIM pin on first boot in lemonadep 

### ISSUE THREAD

**Issue by eirisdg** [BlissRoms/bug_reports#42]
## Describe the bug
Asked 4 times for the SIM pin on first boot in lemonadep  after a fresh install.

## Steps To Reproduce
1. Fresh install
2. First but with SIM card inserted 
3. Asked for 4 times the pin

## Expected Behavior

```
Being asked only one time.
```

## Current Behavior

```
Being asked 4 times
```

## Possible Solution

```
Edit here
```

## Screenshots

```
Edit here
```

## Device Details (please complete the following information)

* Device: lemonadep (OnePlus 9 pro EU)
* Codename: lemonadep
* Build Date: Bliss-v16.0-lemonadep-OFFICIAL-gapps-20221022
* Firmware: C.65

**Comment by StudioKeys** [comment]
@Jackeagle this could be closed now since we r past QPR1
