### ISSUE TITLE
[BUG] Some videos cannot be played due to a sound issue

### ISSUE THREAD

**Issue by eirisdg** [BlissRoms/bug_reports#43]
## Describe the bug
In apps like Twitter or Chrome, the is a bug trying to play some videos. In some times, after changing between some apps, the videos cannot be played. In Twitter it says that another app is using sound. In Chrome simply doesn't play.

## Steps To Reproduce
1. Open many apps with video play
2. Change back to Twitter and try to play a video

## Expected Behavior

```
All videos must be played
```

## Current Behavior

```
Edit here
```

## Possible Solution

```
Closing all apps fix temporally the issue
```

## Screenshots

```
![Screenshot_20221106-121237](https://user-images.githubusercontent.com/5367659/200167512-c0d7d484-f7c9-4d3c-a3a6-bdde14a603ba.png)

```

## Device Details (please complete the following information)

* Device: OnePlus 9 pro
* Codename: lemonadep
* Build Date: Bliss-v16.0-lemonadep-OFFICIAL-gapps-20221022
Firmware: C.65

**Comment by StudioKeys** [comment]
Closing this as we are past QPR1
