### ISSUE TITLE
Update notifier won't go away

### ISSUE THREAD

**Issue by Siarune** [BlissRoms/bug_reports#44]
Device: Pixel 4a
Codename: Sunfish
Build date: v15.6 - 2022-06-19
Originally installed through the 15.2 build posted on the [xda-developer forum](https://forum.xda-developers.com/t/official-blissroms-15-arcadia-sunfish-android-12.4412299/). Default factory image and Linux (sh) install script. 

Even after updating the system from 15.2 to 15.6, the update warning continues to show up. Update was installed through native OTA updater.

## Update Notifier
![Screenshot_20221104-214255_Google Play services](https://user-images.githubusercontent.com/63128110/200189799-463ae0eb-a73a-4ad2-b1b8-07234685a1d4.png)

## OTA Updater
![Screenshot_20221103-085402_Pixel Launcher](https://user-images.githubusercontent.com/63128110/200189801-5b536d76-9597-4e5d-ad43-86f2bf485903.png)

**Comment by StudioKeys** [comment]
Closing this as these were fixed in later builds
