### ISSUE TITLE
[BUG] fast share shows slow charge

### ISSUE THREAD

**Issue by eirisdg** [BlissRoms/bug_reports#45]
## Describe the bug
While charging with fast charger, in lock screen, it says slow charge

## Expected Behavior

```
Show “fast charging” on lockscreen
```

## Current Behavior

```
Shows “slow charging” on lockscreen
```

## Screenshots

![Screenshot_20221106-234510](https://user-images.githubusercontent.com/5367659/200199555-bae1596d-b99f-43af-aed5-8d6ea9c75d4b.png)

## Device Details (please complete the following information)

Device: OnePlus 9 pro
Codename: lemonadep
Build Date: Bliss-v16.0-lemonadep-OFFICIAL-gapps-20221022
Firmware: C.65

**Comment by ericswpark** [comment]
@eirisdg I’ve edited your OP to remove unfilled sections

**Comment by StudioKeys** [comment]
Tried changing cables or charging bricks?
