### ISSUE TITLE
[BUG] "java.lang.SecurityException: Permission Denial" popup every time the OS finishes loading

### ISSUE THREAD

**Issue by rizzini** [BlissRoms/bug_reports#46]
## Describe the bug
I can't see any erratic behavior. I'm filing a bug report because it's possible it worth investigate. It happens on every new install I make. 

## Steps To Reproduce
1. Do a new install of the Bliss v11.14(extended build information below) on a VM using QEMU.

## Expected Behavior

```
Not show an exception popup every time I start the OS.
```

## Current Behavior

```
I didn't see any erratic behavior yet, except this popup that appears every time I start the OS.
```

## Possible Solution

```
I have no idea.
```

## Screenshots

![2022-11-23_05-10](https://user-images.githubusercontent.com/1186150/203499482-93e3081b-70cb-4f8b-b8a7-e004fa2fc708.png)

[logcat](https://pastebin.com/xregHMC4). The error can be seen in lines 3675 and 3683.

## Device Details (please complete the following information)

* Device: Virtual machine. I'm running QEMU thought this [script](https://github.com/rizzini/DotfilesGentooHome/blob/master/Documentos/scripts/start_android_qemu.sh) I made.
* Codename: 
* Build Date: Bliss-v11.14--OFFICIAL-20210507-2246_x86_64_k-google-5.10.32-lts-pledge-xanmod_m-20.1.10_pie-x86_dgc-p9.0-11.13_ld-p9.0-x86_dg-_dh-blueprint_pie-x86_w45_2020_mg-p9.0-x86

**Comment by NextWork123** [comment]
Hello, please redirect this bug to this repository: https://github.com/BlissRoms-x86/support

Best Regards,
NextWorks
