### ISSUE TITLE
[BUG] VPN footer shows in Quick settings even after turning off show security footer

### ISSUE THREAD

**Issue by Saitama310** [BlissRoms/bug_reports#5]
I connected to vpn and that I'm connected to a vpn message showed in quick settings as well as in extended QS panel. I disabled the show security footer ( method to solve on bliss community for vpn bug) but that message that I'm connected to a vpn was  still there ( only in QS panel not in extended QS panel this time). I rebooted my device as well but it didn't worked either .

**Expected behavior**
 

The  VPN footer should have be gone from qs settings all together but it still showed up .

**Screenshots**

![Screenshot_20200508-175613](https://user-images.githubusercontent.com/65023198/81407060-5c4e3400-9158-11ea-83c8-b6d3101d1620.jpg)

![Screenshot_20200508-175558](https://user-images.githubusercontent.com/65023198/81407070-653f0580-9158-11ea-9e89-b64f30503e19.jpg)

**BlissRoms source:**

**Device:**
 Redmi  note 7/7S
 - Codename  - Lavender
 - Build date  - May 6 2020 bliss version 12.7

**Comment by rohanpurohit** [comment]
Well show security footer only removes it from extended qs panel, but can be extended to hide in quick panel as well.. will be added soon

**Comment by rohanpurohit** [comment]
https://github.com/BlissRoms/platform_frameworks_base/commit/88dd5c173a7ec34b4c1f805bbcd7f1cd2dbcc404
