### ISSUE TITLE
[BUG] Google Photos won't upload. Says "Device is too hot"

### ISSUE THREAD

**Issue by ganesh3s3** [BlissRoms/bug_reports#50]
## Describe the bug
I have Bliss ROM 16.5 (Now updated to 16.6) installed on my ASUS ROG Phone 3. 

Ever since I moved from Stock to Bliss, I am unable to upload to Google photos. It has been telling me, "Your device is too hot"  for the past week while my device is not actually hot. It also detects my device as a Pixel device.

I have tried clearing the Google Photos app storage multiple times to no avail.

## Steps To Reproduce
1. Move from the latest stock OS (Android 12) on the Asus ROG Phone 3
2. Install Google Photos from Play Store.
3. Take a photo using the phone's camera.
4. Google photos reports that the device is too hot.

## Expected Behavior

```
Should be able to upload to Google photos without any issues.

```

## Current Behavior

```
Google photos reports that the device is too hot and won't upload.
```

## Possible Solution

```

```

## Screenshots

```
![IMG_20230508_205244](https://user-images.githubusercontent.com/13646665/236866802-35bcd700-186c-4c76-a5a4-d362dc32bbd6.jpg)
```

## Device Details (please complete the following information)

* Device: ASUS ROG Phone 3
* Codename: obiwan
* Build Date: Bliss-v16.5-obiwan-OFFICIAL-gapps-20230328.zip, Bliss-v16.6-obiwan-OFFICIAL-gapps-20230426.zip

**Comment by StudioKeys** [comment]
Will be looked upon👍🏻
