### ISSUE TITLE
[BUG] Calculator app graphic error

### ISSUE THREAD

**Issue by People-11** [BlissRoms/bug_reports#52]
## Describe the bug
The button in the calculator App looks like it's been squashed

## Steps To Reproduce
1. Open yetCalc App

## Expected Behavior

```
It should be perfect circle isn't it?
```

## Current Behavior

```
The button in the calculator App looks like it's been squashed
```

## Possible Solution

```
Edit here
```

## Screenshots

![Screenshot_20230525-015651](https://github.com/BlissRoms/bug_reports/assets/41558215/199ef42e-cc62-4080-a5b5-a9bd27ac23b8)

## Device Details (please complete the following information)

* Device: Zenfone 9 AI2022
* Codename: Typhoon
* Build Date: Bliss-v16.7-AI2202-OFFICIAL-gapps-20230521

**Comment by hmtheboy154** [comment]
This is not a bug, more like YetCalc choice, a suggestion for a better UI is already been made here
https://github.com/Yet-Zio/yetCalc/issues/45
