### ISSUE TITLE
[BUG] Bunch of generic issues

### ISSUE THREAD

**Issue by eremitein** [BlissRoms/bug_reports#6]
Hello, bugs below easily reproducible (and also exists in some others ROMs, but not in the LineageOS/pure AOSP), any developers can check it themself, so no logs attached

**Steps To Reproduce & bugs list**
* install BlissRom without Gapps (not all users want gapps, as you know)
(sorry, but i collected all bugs in on post)
1. in stock dialer try to remove some entry in calls history (see screenrecords). it's not removed until app interface re-draw
2. same error have stock file-manager (try to delete file on internal storage). i guess, those two issues linked between
3. in Bliss launcher impossible to activate notifications dots (see screenrecords). tap on launcher option opens Notification Settings window and after activating option Allow notification dots this is still not work. after leaving that menu, option turns off again (device not a lowram)
4. without gapps incorrectly shows all google sounds in Sound settings (see screnshot below). i fixed it with [this patch](https://github.com/eremitein/treble-patches/blob/caos/patches/frameworks_base/0015-Q-Google-sounds-fix-derp.patch)
5. quick pin unlock behavior (see screenshot) have a bug - if you put a long wrong number, then even after cleaning input bar and even if you re-input right code you can't unlock phone. need lock phone again (turning off screen), then wake it up and insert right code

**Screenshots & screenrecords**
![Screenshot_20200508-012345](https://user-images.githubusercontent.com/12787224/81463942-200de880-91d7-11ea-8adf-7fe93d21a7da.jpg)
![photo_2020-05-09_09-24-49](https://user-images.githubusercontent.com/12787224/81463946-2603c980-91d7-11ea-884e-594f7b5513f4.jpg)
link to screenrecord with bug 1 https://t.me/Team_Bliss_Community/65070
link to screenrecord with bug 3 https://t.me/Team_Bliss_Community/64941

**BlissRoms source:**
v12.7 at the 2020.05.07

**Device:**
independent at device, generic issue (took from GSI build)

**Comment by ericswpark** [comment]
@eremitein , it's hard to act on the bugs when it's all lumped together into one report. Would you mind filing separate reports for each bug? Thank you!

**Comment by efullz** [comment]
@
please fix it.

**Comment by ericswpark** [comment]
Closing issue as they are not reproducible in latest builds (1, 2, and 3). For the remaining issues, please file separate bug reports. Thanks!
