### ISSUE TITLE
[BUG] Data icon glitch

### ISSUE THREAD

**Issue by People-11** [BlissRoms/bug_reports#65]
### Issue type

User interface

### Device

Zenfone 9 AI2022

### Bliss build

16.7

### Bug Description

Data icon glitch, what was an x becomes a black square

### Steps to reproduce

I switched the system icon to Filled and turned off data

### Expected Behavior

It should be a x there.

### Current Behavior

The x disappeared and only a black square left

### Relevant log (logcat/build log)

```shell
no logs can be provided sorry
```

### Screenshots or videos

![Screenshot_20230531-004820_设置](https://github.com/BlissRoms/bug_reports/assets/41558215/f386a67c-9b29-437d-93ad-e0b8dc9c6a63)

### Possible Solution

Maybe the x icon missed?

### Acknowledgements

- [X] I have searched the existing issues before creating a new one.
- [X] I have provided a clear and concise title for the issue.
- [X] I have filled out all the relevant sections above.
- [X] I have attached any necessary screenshots or files.
- [X] I have tested the latest BlissRoms version to confirm if the issue still exists.
- [X] I have filled out all of the requested information in this issue properly.
- [X] I am willing to provide additional information or test steps if requested.

**Comment by StudioKeys** [comment]
This is by default from Google and we are no one who is gonna change it, btw you could use data disable hide from Blissify if that bothers u a lot :)
