### ISSUE TITLE
[BUG] no sound

### ISSUE THREAD

**Issue by bartoszluka** [BlissRoms/bug_reports#66]
after flashing the latest version of the rom (16.7) on my ASUS Zenfone 9 there is no sound at all (ring, media, alarms, touch sounds). I checked that on the stock rom there is sound so it is definitely a rom issue

**Comment by StudioKeys** [comment]
Sorry its not a ROM issue, since it works fine on your maintainer's device

**Comment by Jackeagle** [comment]
There is no such issue on my device and even others who installed it has no such issues either. Sound is perfectly working fine.
