### ISSUE TITLE
[BUG] <!-- Add your summary of the bug faced here -->

### ISSUE THREAD

**Issue by morarity123** [BlissRoms/bug_reports#71]
### Issue type

Feature not working as intended

### Device

ROG Phone2(I001D)

### Bliss build

Bliss-v16.9.1-I001D-OFFICIAL-gapps-20230930_2

### Bug Description

This WiFi function is not working, it continues to connect and save, and once connected, it immediately chooses to disconnect, regardless of which network. The password is correct.
![Screenshot_20230930-174404_Settings](https://github.com/BlissRoms/bug_reports/assets/49313523/8d61d8ce-3171-4ecc-8c1e-fb4e465b3f94)
![Screenshot_20230930-174400_Settings](https://github.com/BlissRoms/bug_reports/assets/49313523/86cedaba-5f9b-45cd-a051-2046e2a15e4f)
 

### Steps to reproduce

1.Connect to the wifi
2.watch he dance

### Expected Behavior

Wifi wont work

### Current Behavior

This WiFi function is not working

### Relevant log (logcat/build log)

```shell
nop
```

### Acknowledgements

- [X] I have searched the existing issues before creating a new one.
- [X] I have provided a clear and concise title for the issue.
- [X] I have filled out all the relevant sections above.
- [X] I have attached any necessary screenshots or files.
- [X] I have tested the latest BlissRoms version to confirm if the issue still exists.
- [X] I have filled out all of the requested information in this issue properly.
- [X] I am willing to provide additional information or test steps if requested.

**Comment by StudioKeys** [comment]
Its working on our end as expected so im closing this up
I did personally test..

Cheers,
StudioKeys
