### ISSUE TITLE
[BUG] The home screen dock app grid stays same

### ISSUE THREAD

**Issue by SudipRajbanshi** [BlissRoms/bug_reports#72]
### Issue type

Feature not working as intended

### Device

Poco X2 (phoenixin)

### Bliss build

Bliss 17.1 official vanilla UQ1A.240105

### Bug Description

In the bliss launcher's home screen dock app grid stays same, means-
If I change the app grid from wallpaper and style expected behaviour is the home screen dock app grid also should adopt the grid size i've selected, but it says 5 apps even though i have selected the 4x5 grid. The home screen (accept the dock), app drawer grid changes accordingly. I only faced this issue with 4x5 grid.

### Steps to reproduce

Step1. Choose the app grid 4x5 from the wallpaper and style. And you'll notice that the dock apps are 5 instead of 4

### Expected Behavior

The dock apps should follow 4x5 grid

### Current Behavior

The app grid stays as 5 icons

### Relevant log (logcat/build log)

```shell
None
```

### Screenshots or videos

![Screenshot_20240124-223046_Blissify_Home](https://github.com/BlissRoms/bug_reports/assets/98258654/0af5ce91-f754-47c7-ac1a-ad940abe959b)
![Screenshot_20240124-223017_Blissify_Home](https://github.com/BlissRoms/bug_reports/assets/98258654/a27a5f56-306d-4d24-9645-31f98916d58b)

### Possible Solution

Make the dock follow 4x5 grid

### Acknowledgements

- [X] I have searched the existing issues before creating a new one.
- [X] I have provided a clear and concise title for the issue.
- [X] I have filled out all the relevant sections above.
- [X] I have attached any necessary screenshots or files.
- [X] I have tested the latest BlissRoms version to confirm if the issue still exists.
- [X] I have filled out all of the requested information in this issue properly.
- [X] I am willing to provide additional information or test steps if requested.

**Comment by RomenDiojen** [comment]
Very informative indeed

**Comment by SudipRajbanshi** [comment]
Sorry sir those are wrong screenshots as you can tell by now.
![Screenshot_20240124-223017_Blissify_Home](https://github.com/BlissRoms/bug_reports/assets/98258654/0466d29c-acff-4fd0-a12d-f2464be31bd7)

**Comment by SudipRajbanshi** [comment]
Sorry sir those are wrong screenshots as you can tell by now.
![Screenshot_20240124-223046_Blissify_Home](https://github.com/BlissRoms/bug_reports/assets/98258654/22c21292-1461-472d-9e43-3f40ce9d31bb)

**Comment by StudioKeys** [comment]
Will be looked upon as the bug is present on our end too....

Cheers,
StudioKeys

**Comment by StudioKeys** [comment]
Fixed for v17.2 so closing this up
