### ISSUE TITLE
[BUG] Volume panel not working properly (Poco X2 || Bliss v17.2)

### ISSUE THREAD

**Issue by jagadish8550** [BlissRoms/bug_reports#77]
### Issue type

Feature not working as intended

### Device

phoenix

### Bliss build

v17.2 - 2024-02-12 GApps build

### Bug Description

Volume panel will act different than usual when after sometime of up time. Cannot increase or decrease volume as we do usually when happens.

Appreciate the work of dev and maintainers who made this wonderful rom.
Not expecting you to mandatorily fix this but thought it might help you make the rom and user experience better.

### Steps to reproduce

It starts happenening at some randomtime of up time.

### Expected Behavior

Volume panel should work as usual by showing the media volume in the panel.

### Current Behavior

media volume conrtol is displayed away from panel and does not work until expanded.

### Relevant log (logcat/build log)

```shell
No logs available
```

### Screenshots or videos

https://github.com/BlissRoms/bug_reports/assets/96580356/edc4069e-72c0-4dfd-bbcb-983c827283b7

### Acknowledgements

- [X] I have searched the existing issues before creating a new one.
- [X] I have provided a clear and concise title for the issue.
- [X] I have filled out all the relevant sections above.
- [X] I have attached any necessary screenshots or files.
- [X] I have tested the latest BlissRoms version to confirm if the issue still exists.
- [X] I have filled out all of the requested information in this issue properly.
- [X] I am willing to provide additional information or test steps if requested.

**Comment by StudioKeys** [comment]
This is a Google AOSP which was addressed for v17.4
So it should have it fixed
Closing this issue hence....
