### ISSUE TITLE
Theme "muted" crash  issue

### ISSUE THREAD

**Issue by AmitSharma94** [BlissRoms/bug_reports#83]
### Issue type

Feature not working as intended

### Device

sky

### Bliss build

Bliss-v17.4-sky-OFFICIAL-gapps-20240505.zip

### Bug Description

Under the blissify menu when we go to Theme settings and set the theme "muted" the wallpaper and style settings crashes

### Steps to reproduce

Step 1 : go to Blissify
Step 2 : go the themes
Step 3 : go to theming settings and set theme style "muted"
Step 4 : go back to main settings menu
Step 5 : tap on wallpaper and style

It should crash there

### Expected Behavior

Wallpaper and Styles should have worked

### Current Behavior

Currently it crashes and I have shifted to other theme options to use wallpaper and style option under the settings

### Relevant log (logcat/build log)

```shell
https://bin.kv2.dev/~663f340d5de7ed6bfdc31efe
```

### Screenshots or videos

![Screenshot_20240511-144539](https://github.com/BlissRoms/bug_reports/assets/39725899/e00af76e-e525-48b7-9139-07dcfddda69c)

### Acknowledgements

- [X] I have searched the existing issues before creating a new one.
- [X] I have provided a clear and concise title for the issue.
- [X] I have filled out all the relevant sections above.
- [X] I have attached any necessary screenshots or files.
- [X] I have tested the latest BlissRoms version to confirm if the issue still exists.
- [X] I have filled out all of the requested information in this issue properly.
- [X] I am willing to provide additional information or test steps if requested.

**Comment by StudioKeys** [comment]
Fixed and the new build with the fixed with roll out on v17.5 

Fix :- https://github.com/BlissRoms/platform_packages_apps_ThemePicker/commit/40532c5152bfe4ee4f5ff2bc7e33c95f7059f65a

Cheers,
StudioKeys
