### ISSUE TITLE
[BUG] Minor spelling correction

### ISSUE THREAD

**Issue by palimatix** [BlissRoms/bug_reports#9]
Negotiate spelling needs to be corrected.
Build 12.7 , Taimen,
![Screenshot_20200522-121015463 (1)](https://user-images.githubusercontent.com/1551851/82640280-ef42a000-9c27-11ea-8c7b-a80329be116f.jpg)
 
20/5/2020

**Comment by ericswpark** [comment]
Hello, the mistake has been corrected. Thanks!
